version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_pgadmin_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: cybersecurity_local_django
    container_name: cs_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cybersecurity_production_postgres
    container_name: cs_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres

  pgadmin:
    build:
      context: .
      dockerfile: ./compose/production/pgadmin/Dockerfile
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: SecretCode
      PGADMIN_LISTEN_PORT: 5050
    logging:
      driver: none
    ports:
      - "5050:5050"
    volumes:
      - local_pgadmin_data:/var/lib/pgadmin:z

  docs:
    image: cybersecurity_local_docs
    container_name: cs_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./cybersecurity:/app/cybersecurity:z
    ports:
      - "7000:7000"
    command: /start-docs
