# Generated by Django 3.0.12 on 2021-02-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=125)),
                ('day', models.CharField(max_length=125)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
