# Generated by Django 3.0.12 on 2021-02-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tema3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=125)),
                ('hashtag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TempSentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=125)),
                ('sentiment', models.CharField(max_length=125)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
